// rootana_config.h
// generated by rootana Makefile Tue Apr 10 10:37:36 SAST 2018
//
#define HAVE_MIDAS 1
//#define MIDASSYS /usr/physics/midas
#define HAVE_LIBZ 1
#define HAVE_ROOT 1
//#define ROOTSYS /usr/physics/root/root-build
//#define HAVE_ROOT_HTTP 1
#define HAVE_ROOT_XML 1
//#define HAVE_THTTP_SERVER 1
#define HAVE_XMLSERVER 1
#define HAVE_LIBNETDIRECTORY 1
// end
